#!/usr/bin/env python3
"""Extract the message exchange between coordinating sessions as a markdown log.

    agent-chatter --log notes.md
        -o coordination-log.md

Plain text on purpose. The HTML dashboard is better for exploring; this is better
for grepping, diffing, reviewing in a PR, and committing next to the work it
describes. Pass every session's transcript — the model deduplicates the sender's
and receiver's copies of one message rather than counting it twice.

This used to carry its own parser. It no longer does: `chatter/model.py` is the
single model and this file only formats. The old parser matched
`<cross-session-message[^>]*>`, which matches any text that merely *describes* the
format, so reading this repo's own source fabricated messages and attributed them
to a real peer. It also knew nothing about mid-turn deliveries, which exist only
as queue records, and so silently dropped the majority of inbound traffic on a
busy session.

SECRETS: output is scrubbed by `chatter/scrub.py` before writing. A transcript
contains anything that was pasted into the session, including credentials, and
this file gets committed. See AGENTS.md for the check to run afterwards — and note
that no output from that check means it did not run.
"""
import argparse
import os
import re
import sys

from . import model


def fmt(stamp):
    """Full ISO stamp, kept as recorded. The previous version formatted "%H:%M"
    and dropped the date, which is wrong for any mesh running over midnight."""
    return stamp or "—"


def render(data, title):
    events = data["events"]
    sessions = data["sessions"]

    def who(sid):
        s = sessions.get(sid) or {}
        return s.get("name") or sid or "unknown"

    peer = [e for e in events if e["kind"] != "human"]
    humans = len(events) - len(peer)
    per = {}
    for e in peer:
        per[e["from_id"]] = per.get(e["from_id"], 0) + 1

    out = [
        f"# {title}",
        "",
        "Every message exchanged between the coordinating agent sessions, in",
        "order. Generated by `agent-chatter --log` — **do not edit by",
        "hand**; re-run the command instead.",
        "",
        "A commit records that a decision changed. It does not record that the",
        "other session caught the error, what it argued, or what was rejected on",
        "the way. That is what this is for.",
        "",
        f"**{len(peer)} messages** between {len(sessions)} sessions"
        + (f", plus {humans} human turn{'s' if humans != 1 else ''}" if humans else "")
        + ".",
        "",
    ]
    for sid in sorted(per, key=lambda s: -per[s]):
        ghost = " *(no transcript held)*" if (sessions.get(sid) or {}).get("ghost") else ""
        out.append(f"- **{who(sid)}** — {per[sid]} sent{ghost}")
    out += ["", "Timestamps are as recorded in the transcript (UTC).", "", "---", ""]

    for i, e in enumerate(events, 1):
        if e["kind"] == "human":
            out.append(f"## {i}. {fmt(e['delivered'] or e['enqueued'])} · human → {who(e['to_id'])}")
        else:
            out.append(f"## {i}. {fmt(e['sent'] or e['enqueued'])} · "
                       f"{who(e['from_id'])} → {who(e['to_id'])}")
        if e.get("summary"):
            out.append(f"**{e['summary'].strip()}**")
        out.append("")

        # Three clocks, each labelled. A single rendered time would be a silent
        # choice about which one; a missing recipient clock is the delivery
        # signal, not absent data.
        clocks = []
        if e.get("sent"):
            clocks.append(f"sent `{e['sent']}`")
        for key, label in (("enqueued", "arrived"), ("delivered", "read")):
            clocks.append(f"{label} `{e[key]}`" if e.get(key) else f"{label} *not held*")
        if e.get("delivery"):
            clocks.append(f"delivery `{e['delivery']}`")
        if e.get("sides") == "out":
            clocks.append("**never landed** — no recipient transcript contains it")
        elif e.get("sides") == "in":
            clocks.append("**unconfirmed** — no sending transcript held")
        out.append("· ".join(c + " " for c in clocks).strip())
        out += ["", "```", (e.get("body") or "").strip(), "```", ""]

    return "\n".join(out) + "\n"


_CONTROL = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


def visible_controls(text):
    """Escape control bytes so the log stays a text file.

    render.py REFUSES to emit a NUL, because there it can only come from the
    template and the author can fix it. Here it comes from a message body and
    refusing would mean the log cannot be written at all, so the byte is escaped
    instead — same goal, different remedy.

    Why it matters: one NUL anywhere makes grep classify the whole file as
    binary, and the credential scan this repo tells you to run before sharing
    then matches nothing and looks clean. Found by grepping a real log and
    getting silence — the byte came from a message discussing this very bug,
    which had been fixed for the HTML path and never for this one. Tab and the
    newlines are left alone; they are the only control characters markdown wants.
    """
    return _CONTROL.sub(lambda m: "\\x%02x" % ord(m.group(0)), text)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("transcripts", nargs="+")
    ap.add_argument("-o", "--out", default="coordination-log.md")
    ap.add_argument("--title", default="Coordination log",
                    help="heading for the generated document")
    args = ap.parse_args()

    paths = [t for t in args.transcripts if os.path.exists(t)]
    for t in args.transcripts:
        if t not in paths:
            print(f"skip (missing): {t}", file=sys.stderr)
    if not paths:
        sys.exit("no readable transcripts")

    data = model.build(paths)
    if not data["events"]:
        sys.exit("no peer messages found")

    text = visible_controls(render(data, args.title))

    # Bodies are already scrubbed by the model. Assert rather than trust: this
    # file gets committed, and a silent regression here costs a credential.
    from .scrub import has_secret
    if has_secret(text):
        sys.exit("refusing to write: output still matches the credential pattern")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    peer = sum(1 for e in data["events"] if e["kind"] != "human")
    print(f"{args.out}: {peer} messages, {len(data['sessions'])} sessions")


if __name__ == "__main__":
    main()
